version: "3.9"

services:
  bootnode:
    image: thor:latest
    container_name: thor-bootnode
    entrypoint: /usr/bin/thor --data-dir /root/node --network /root/genesis.json --nat extip:172.99.1.1 
    ports:
      - "18669:8669"
      - "11235:11235"
    volumes:
      - ./config/bootnode:/root/.org.vechain.thor
      - ./config/genesis.json:/root/genesis.json
      - ./data/bootnode:/root/node
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 100
        window: 120s
    networks:
      thor-testnet:
        ipv4_address: 172.99.1.1

  node1:
    image: thor:latest
    container_name: thor-node-1
    entrypoint: /usr/bin/thor --data-dir /root/node --network /root/genesis.json --nat extip:172.99.1.2 --api-addr "0.0.0.0:8669" --bootnode "enode://bc18b2d7dd0daf50073f53f5c8e7aecb41387275efb5fd0e41ec3b87ce2804353692c38a9774777ce39ba0de61648cd7adc70d3fc29692b46c5f520f542a7824@172.99.1.1:11235"
    ports:
      - "28669:8669"
      - "21235:11235"
    volumes:
      - ./config/node1:/root/.org.vechain.thor
      - ./config/genesis.json:/root/genesis.json
      - ./data/node1:/root/node
    depends_on:
      - bootnode
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 100
        window: 120s
    networks:
      thor-testnet:
        ipv4_address: 172.99.1.2

  node2:
    image: thor:latest
    container_name: thor-node-2
    entrypoint: /usr/bin/thor --data-dir /root/node --network /root/genesis.json --nat extip:172.99.1.3 --api-addr "0.0.0.0:8669" --bootnode "enode://bc18b2d7dd0daf50073f53f5c8e7aecb41387275efb5fd0e41ec3b87ce2804353692c38a9774777ce39ba0de61648cd7adc70d3fc29692b46c5f520f542a7824@172.99.1.1:11235"
    ports:
      - "38669:8669"
      - "31235:11235"
    volumes:
      - ./config/node2:/root/.org.vechain.thor
      - ./config/genesis.json:/root/genesis.json
      - ./data/node2:/root/node
    depends_on:
      - bootnode
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 100
        window: 120s
    networks:
      thor-testnet:
        ipv4_address: 172.99.1.3

  node3:
    image: thor:latest
    container_name: thor-node-3
    entrypoint: /usr/bin/thor --data-dir /root/node --network /root/genesis.json --nat extip:172.99.1.4 --api-addr "0.0.0.0:8669" --bootnode "enode://bc18b2d7dd0daf50073f53f5c8e7aecb41387275efb5fd0e41ec3b87ce2804353692c38a9774777ce39ba0de61648cd7adc70d3fc29692b46c5f520f542a7824@172.99.1.1:11235"
    ports:
      - "48669:8669"
      - "41235:11235"
    volumes:
      - ./config/node3:/root/.org.vechain.thor
      - ./config/genesis.json:/root/genesis.json
      - ./data/node3:/root/node
    depends_on:
      - bootnode
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 100
        window: 120s
    networks:
      thor-testnet:
        ipv4_address: 172.99.1.4

networks:
  thor-testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/16
